apiVersion: v2
name: ingress
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: ingress-nginx
    version: "4.0.10"
    repository: https://kubernetes.github.io/ingress-nginx
