apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sumer-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: web-dapp
      port:
        number: 3000
  rules:
    - http:
        paths:
          - path: /rest
            pathType: Prefix
            backend:
              service:
                name: rest-gateway
                port:
                  number: 5000
          - path: /io
            pathType: Prefix
            backend:
              service:
                name: websocket-gateway
                port:
                  number: 4000
          - path: /grafana/?(.*)
            pathType: Prefix
            backend:
              service:
                name: grafana
                port: 
                  number: 9000
